= IsyFact-Benutzerverwaltung
:sourcedir: src/main/java
:webappdir: src/main/webapp

Die IsyFact-Benutzerverwaltung stellt eine leichtgewichtige Software-Komponente zur Verwaltung von Benutzern und Rollen bereit und ist vor allem für kleine, eigenständige Anwendungen gedacht.
Anwendungen können mithilfe der Komponente auf einfache Weise:

* Benutzer und Rollen verwalten,
* eine IsyFact-konforme Absicherung der Anwendung erzielen,
* vorgefertigte grafische Oberflächen für die Verwaltung von Benutzern und Rollen sowie zur An- und Abmeldung von Benutzern einsetzen.

Die IsyFact-Benutzerverwaltung stellt keine Möglichkeit eines Single Sign On (SSO) bereit.
Jede Anwendung besitzt eigene Benutzer und Rollen.

Die Einbindung der einzelnen Module wird in der jeweiligen Moduldokumentation beschrieben.

https://github.com/IsyFact/isyfact-benutzerverwaltung/blob/master/isy-benutzerverwaltung-core/src/docs/asciidoc/isy-benutzerverwaltung-core.adoc[Dokumentation `isy-benutzerverwaltung-core`]

https://github.com/IsyFact/isyfact-benutzerverwaltung/blob/master/isy-benutzerverwaltung-core/src/docs/asciidoc/isy-benutzerverwaltung-sicherheit.adoc[Dokumentation `isy-benutzeverrwaltung-sicherheit`]

https://github.com/IsyFact/isyfact-benutzerverwaltung/blob/master/isy-benutzerverwaltung-core/src/docs/asciidoc/isy-benutzerverwaltung-gui-primefaces.adoc[Dokumentation `isy-benutzvererwaltung-gui-primefaces`]

https://github.com/IsyFact/isyfact-benutzerverwaltung/blob/master/isy-benutzerverwaltung-core/src/docs/asciidoc/isy-benutzerverwaltung-gui-tomahawk.adoc[Dokumentation `isy-benutzerverwaltung-gui-tomahawk`]

////
== Anleitung zur Einbindung

=== GUI allgemein
* Inhalt der `gui-linksnavigation.properties` in die entsprechende Datei der Anwendung kopieren und die Liste der IDs zusammenführen.
* Inhalt der `navigation.xml` mit der entsprechenden Datei der Anwendung zusammenführen.

=== GUI mit Primefaces
* `basis.xhtml` der Bibliothek `plis-web` überschreiben und Import von `jQuery` herausnehmen.

.Konfiguration der FontAwesome-Icons
[source,xml]
----
<context-param>
    <param-name>primefaces.FONT_AWESOME</param-name>
    <param-value>true</param-value>
</context-param>
----
////