ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Einbinden von _isy-benutzerverwaltung-core_
-------------------------------------------

In diesem Abschnitt wird beschrieben, wie man das Modul `isy-benutzerverwaltung-core` in die eigene Anwendung integriert.
Nach der Einbindung kann mit Hilfe der Schnittstelle 

    de.bund.bva.isyfact.benutzerverwaltung.core.benutzerverwaltung.Benutzerverwaltung
    
beispielsweise eine eigene grafische Oberfläche geschrieben werden, um auf die Funktionen  (z.B. Anlegen, Suchen und Löschen von Benutzern) der Benutzerverwaltung zuzugreifen.

Maven
~~~~~

Zur Integration der Kernkomponente muss die Anwendung die folgende Abhängigkeit in ihrem POM definieren:

[source,xml]
----
<dependency>
    <groupId>de.bund.bva.isyfact.benutzerverwaltung</groupId>
    <artifactId>isy-benutzerverwaltung-core</artifactId>
    <version>1.4.2</version>
</dependency>
----

Datenbank
~~~~~~~~~

Um die für die _IsyFact-Benutzerverwaltung_ benötigten Tabellen anzulegen gibt es mehrere Möglichkeiten.

- In der Datei `jpa.properties` den Parameter `database.schema.updatemode=create` setzen. 

WARNING: Beim nächsten Start der Anwendung werden alle Tabellen neu erstellt.

- Zum Erzeugen der benötigten Tabellen kann auch das folgende SQL-Skript ausgeführt werden:
  `isy-benutzerverwaltung\src\main\resources\resources\isy-benutzerverwaltung\skripte\sql\isy-Benutzerverwaltung-tabellen-anlegen.sql`

Für die Komponente `isy-benutzerverwaltung-core` werden drei Tabellen benötigt:

- `Benutzer`
- `Rollen`
- `Benutzer_Rollen`

Die Rollen werden in der Datenbank gespeichert.
Die Zuordnung von Rechten zu Rollen geschieht aber in der Datei `rollenrechte.xml`.
Damit diese Zuordnung funktioniert, müssen die vergebenen _Rollen-IDs_ der Datenkbank mit denen aus der `rollenrechte.xml` übereinstimmen.
Zum Aufbau der Datei `rollenrechte.xml` sei auf das https://github.com/IsyFact/IsyFact-Standards/blob/master/20_Bausteine/Sicherheitskomponente/Nutzerdokumentation_Sicherheit.pdf[Nutzerdokumentation Sicherheit] verwiesen.

Spring
~~~~~~

Die Spring-Konfiguration von `isy-benutzerverwaltung-core` wird folgendermaßen in die eigene Anwendung integriert:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans ...>
    ...
    <!-- isy-Benutzerverwaltung-Modul -->
    <import resource="classpath:resources/isy-benutzerverwaltung/spring/isy-benutzerverwaltung-core-modul.xml" />
    ...
</beans>
----

Wird die Anwendung mittels Annotationen konfiguriert, sieht der Import wie folgt aus:

[source,java]
----
...
@Configuration
...
@ImportResource("classpath:resources/isy-benutzerverwaltung/spring/isy-benutzerverwaltung-core-modul.xml")
...
public class ...
----

Sonstiges
~~~~~~~~~

Persistenz
^^^^^^^^^^

In der Datei `persistence.xml` muss ein Eintrag für die Entities `Benutzer` und `Rolle` hinzugefügt werden.

.persistence.xml
[source,xml,caption="Listing: "]
----
<persistence version="2.1"
	xmlns="http://xmlns.jcp.org/xml/ns/persistence" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
  <persistence-unit name="hibernatePersistence">
    ...
    <!-- Wird für Benutzerverwaltung benötigt -->    
    <class>de.bund.bva.isyfact.benutzerverwaltung.persistence.basisdaten.entity.Benutzer</class>
    <class>de.bund.bva.isyfact.benutzerverwaltung.persistence.basisdaten.entity.Rolle</class>
    <class>de.bund.bva.isyfact.benutzerverwaltung.persistence.selfservice.entity.BenutzerToken</class>
  </persistence-unit>
</persistence>
----

Self-Service
^^^^^^^^^^^^

Die E-Mail-Konfiguration des Self-Service verwendet folgende Properties:

[width="75%", options="header"]
|=====
| Property | Werte / Beispiel | Erklärung
| selfservice.mail.smtp.host       | `mail.example.com` | Hostname des SMTP-Servers
| selfservice.mail.smtp.port       | `465`              | Port des SMTP-Servers
| selfservice.mail.smtp.ssl.enable | `true` / `false`   | SSL ein- oder ausgeschaltet
| selfservice.mail.smtp.auth       | `true` / `false`   | Authentifizierung ein- oder ausgeschaltet.
                                                          Wenn dieser Wert auf `false` steht, können die
                                                          Properties `selfservice.mail.username` und
                                                          `selfservice.mail.password` weggelassen werden.
| selfservice.mail.username        | `self.service@example.com` | Benutzername zur Authentifizierung am SMTP-Server
| selfservice.mail.password        | `self.service` | Passwort zur Authentifizierung am SMTP-Server
| selfservice.mail.sender          | `self.service@example.com` | Absenderadresse
| selfservice.mail.subject         | `Selfservice zum Zurücksetzen Ihres Passworts` | Text für Betreffzeile der E-Mail
| selfservice.mail.body            | `Über folgenden Link setzen Sie Ihr Passwort zurueck:\n\n$link` | Text für den Body der E-Mail.
                                                                                                     Muss Platzhalter `$link` enthalten.
| selfservice.mail.link            | `http://example.com/selfServicePasswortZuruecksetzenFlow?token=` | Text für den `$link`-Platzhalter im Body der E-Mail.
                                                                                                        Der Link muss zum `selfServicePasswortZuruecksetzenFlow` führen.
                                                                                                        An diesen Text wird das Token angehängt und der Link muss entsprechend auf `?token=` oder `&token=` enden.
|=====

Eine Beispieldatei mit allen Properties liegt unter `src/main/resources/config/selfServiceMail.properties`.

Integration in Anwendungen
^^^^^^^^^^^^^^^^^^^^^^^^^^

Da Anwendungen nicht direkt auf die Tabellen der Benutzerverwaltung zugreifen und diese ändern dürfen, müssen sie immer über die Schnittstelle des Anwendungskerns gehen.
Anwendungskomponenten müssen trotzdem Referenzen auf Benutzer speichern können.
Dazu ist zur Integration in die Entitäten der Anwendung die Klasse `BenutzerReferenz` vorgesehen.
Hinweise zur Verwendung sind in der API-Dokumentation der Klasse enthalten.
